version: "3.8"

services: 
  database:
    image: postgres
    container_name: database_fin_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    build:
      context: .
    ports:
      - 3333:3333
    working_dir: /app
    container_name: app_fin_api
    volumes:
      - ./:/app

volumes:
  pgdata:
